### ISSUE TITLE
Exception при запросе GetCities

### ISSUE THREAD

**Issue by jetonz** [Boberneprotiv/NovaPoshtaApi#1]

**Comment by jetonz** [comment]
var np = new NovaPoshta(apiKey);
 var citiesResponse = Task.Run(() => np.GetCities(string.Empty)).Result;

выдаёт ошибку : 
System.AggregateException: 
One or more errors occurred. (Unexpected character encountered while parsing value: [. Path 'data[85].Conglomerates', line 1, position 61301.)'

**Comment by Boberneprotiv** [comment]
Спасибо за замечание. В новой версии будет исправлено

**Comment by Boberneprotiv** [comment]
Можно обновится https://www.nuget.org/packages/NovaPoshtaApi/1.1.3

**Comment by jetonz** [comment]
Спасибо, за фикс. Очень пригодилась библиотека, сэкономила немало времени. Жаль что 
поддержки .net core 1.^ больше нету ((

**Comment by jetonz** [comment]
Может стоило бы в версии 1.^ библиотеки хранить поддержку первой версии .net core и параллельно выпустить версию библиотеки 2.^ со второй корой?

**Comment by Boberneprotiv** [comment]
Это первые наброски, на следующей неделе постараюсь выкатить нормальную версию и добавить поддержку всех платформ

Приходится много тестировать само API т.к. документация не очень хорошая

**Comment by Boberneprotiv** [comment]
> Жаль что поддержки .net core 1.^ больше нету ((

Новую версию собрал для core 1
Обновляйтесь аккуратно, нарушена совместимость,
В ближайшее время интерфейс меняться не будет, только дополнятся
