### ISSUE TITLE
сделать параметры в методе getWarehouses() не обязательными

### ISSUE THREAD

**Issue by jetonz** [Boberneprotiv/NovaPoshtaApi#6]
Метод getWarehouses() обязует передавать параметры cityName и cityRef , хотя ссылаясь на [документацию ](https://devcenter.novaposhta.ua/docs/services/556d7ccaa0fe4f08e8f7ce43/operations/556d8211a0fe4f08e8f7ce45) они не обязательны.

**Comment by Boberneprotiv** [comment]
Добавил метод без параметров
Обновляйтесь аккуратно, нарушена совместимость,
В ближайшее время интерфейс меняться не будет, только дополнятся
